env: "local"
grpc_server:
  host: "localhost"
  port: "50053"
profile_db:
  dsn: "host=localhost user=postgres password=admin dbname=shvark_profile_service port=5432 sslmode=disable"
log_config:
  log_level: "debug"
  log_format: "json"
  log_output: "stdout"